document.documentElement.classList.add("js");

document.addEventListener("DOMContentLoaded", () => {
  const translations = {
    en: {
      "nav.features": "Features",
      "nav.how": "How It Works",
      "nav.use": "Use Cases",
      "nav.tech": "Technology",
      "nav.readiness": "Readiness",
      "nav.roadmap": "Roadmap",
      "nav.partners": "Partners",
      "nav.pricing": "Pricing",
      "nav.origin": "Origin",
      "nav.prototype": "Prototype",
      "nav.vision": "Vision",
      "nav.contact": "Contact",
      "strip.item1": "Ambient vision intelligence",
      "strip.item2": "Real-time scene understanding",
      "strip.item3": "Haptic navigation cues",
      "strip.item4": "Voice-first control",
      "strip.item5": "Assistive accessibility layer",
      "strip.item6": "Secure cloud reasoning",
      "strip.item7": "Hands-free translation",
      "strip.item8": "Bluetooth device mesh",
      "hero.eyebrow": "AI-POWERED WEARABLE INTELLIGENCE",
      "hero.title": "The Future of Wearable AI",
      "hero.subtitle": "Meet RΔS Smartcap",
      "hero.desc":
        "RΔS Smartcap blends camera vision, spatial audio, and cloud AI into a single premium wearable that augments daily life with real-time context and guidance.",
      "hero.tagline": "Not just an technology, it is wearable technology",
      "hero.cta": "Explore the Future",
      "hero.ctaAlt": "Our Vision",
      "hero.metric1": "Context Awareness",
      "hero.metric2": "AI Response Time",
      "hero.metric3": "Always-On Assist",
      "panel.subtitle": "Prototype Intelligence Layer",
      "panel.spec.visionLabel": "Vision",
      "panel.spec.visionValue": "Real-time capture",
      "panel.spec.audioLabel": "Audio",
      "panel.spec.audioValue": "Directional feedback",
      "panel.spec.connLabel": "Connectivity",
      "panel.spec.connValue": "Bluetooth + Cloud AI",
      "panel.footer": "Engineered for seamless daily augmentation.",
      "features.eyebrow": "FEATURES",
      "features.title": "Designed for intelligent living",
      "features.desc": "Every component is purpose-built to deliver ambient intelligence with zero friction.",
      "features.note": "All listed features are available in current prototype builds.",
      "feature1.title": "AI-powered assistant",
      "feature1.desc": "Context-aware support that adapts to your day in real time.",
      "feature2.title": "Camera for real-time analysis",
      "feature2.desc": "Scene understanding with on-device capture and cloud vision.",
      "feature3.title": "Voice interaction",
      "feature3.desc": "Hands-free control through an always-ready microphone array.",
      "feature4.title": "Bluetooth connectivity",
      "feature4.desc": "Seamless pairing with phones, earbuds, and connected devices.",
      "feature5.title": "Accessibility for visually impaired",
      "feature5.desc": "Vibration feedback delivers discreet, directional guidance.",
      "feature.status": "Available in prototype",
      "how.eyebrow": "HOW IT WORKS",
      "how.title": "From capture to response in seconds",
      "how.step1.title": "Capture",
      "how.step1.desc": "Camera & microphone gather real-world inputs around you.",
      "how.step2.title": "Process",
      "how.step2.desc": "Cloud AI interprets context, objects, and intent instantly.",
      "how.step3.title": "Respond",
      "how.step3.desc": "Audio feedback guides your next move with precision.",
      "how.voice.title": "Say \"Hey Ras\"",
      "how.voice.desc":
        "The RΔS AI starts listening instantly and answers your questions with calm, clear guidance.",
      "use.eyebrow": "USE CASES",
      "use.title": "Built for real-world impact",
      "use.case1.title": "Daily life assistance",
      "use.case1.desc": "Schedule reminders, object recognition, and contextual prompts.",
      "use.case2.title": "Accessibility",
      "use.case2.desc": "Enhanced independence for visually impaired users.",
      "use.case3.title": "Travel & navigation",
      "use.case3.desc": "Step-by-step guidance with spatial awareness and alerts.",
      "use.case4.title": "Smart communication",
      "use.case4.desc": "Translate, transcribe, and connect without lifting a phone.",
      "stack.eyebrow": "TECHNOLOGY",
      "stack.title": "A wearable-grade intelligence stack",
      "stack.desc": "Built to deliver low-latency, high-trust assistance in the real world.",
      "stack.card1.title": "Sensor Fusion Core",
      "stack.card1.desc": "Camera, microphone, and motion data blended for rich situational awareness.",
      "stack.card2.title": "Edge + Cloud AI",
      "stack.card2.desc": "Fast on-device filtering with scalable cloud reasoning.",
      "stack.card3.title": "Spatial Feedback Engine",
      "stack.card3.desc": "Directional audio and haptic cues for discreet guidance.",
      "readiness.eyebrow": "READINESS",
      "readiness.title": "Prototype readiness dashboard",
      "readiness.desc": "Current build status across hardware, AI, and human-centered testing.",
      "readiness.card1.title": "Hardware integration",
      "readiness.card1.desc": "Camera, mic array, and haptics validated in prototype.",
      "readiness.card2.title": "AI calibration",
      "readiness.card2.desc": "Context recognition models tuned for real-world use.",
      "readiness.card3.title": "User validation",
      "readiness.card3.desc": "Accessibility feedback and pilot testing in progress.",
      "readiness.card4.title": "Manufacturing readiness",
      "readiness.card4.desc": "Supply chain partners and tooling locked.",
      "roadmap.eyebrow": "ROADMAP",
      "roadmap.title": "A clear path to launch",
      "roadmap.desc": "Focused milestones to move from prototype to pilot and partner deployment.",
      "roadmap.step1.date": "April 18, 2026",
      "roadmap.step1.title": "Prototype complete",
      "roadmap.step1.desc": "Core hardware + AI integration finalized.",
      "roadmap.step2.date": "Q2 2026",
      "roadmap.step2.title": "Pilot programs",
      "roadmap.step2.desc": "Deploy with accessibility partners and field testers.",
      "roadmap.step3.date": "Q3 2026",
      "roadmap.step3.title": "Partner integrations",
      "roadmap.step3.desc": "Secure platform integrations and developer tooling.",
      "roadmap.step4.date": "Q4 2026",
      "roadmap.step4.title": "Limited release",
      "roadmap.step4.desc": "Curated rollout for strategic partners.",
      "partners.eyebrow": "PARTNERS",
      "partners.title": "Built for collaboration",
      "partners.desc": "We are opening a limited partner cohort to validate real-world impact.",
      "partners.card1.title": "Pilot Programs",
      "partners.card1.desc": "Co-design use cases and test in real environments.",
      "partners.card2.title": "Integration Toolkit",
      "partners.card2.desc": "Connect to your platforms with secure data flows.",
      "partners.card3.title": "Enterprise Readiness",
      "partners.card3.desc": "Governance, compliance, and support baked in.",
      "partners.cta": "Request Partner Access",
      "pricing.eyebrow": "PRICING",
      "pricing.title": "Early access pricing",
      "pricing.desc": "Limited founder pricing for the first 10 customers.",
      "pricing.tag": "Founder Offer",
      "pricing.tag2": "Standard",
      "pricing.card1.title": "First 10 sales",
      "pricing.card1.item1": "Prototype priority access",
      "pricing.card1.item2": "Direct feedback channel",
      "pricing.card1.item3": "Early partner updates",
      "pricing.card2.title": "Selling price",
      "pricing.card2.item1": "Production-ready unit",
      "pricing.card2.item2": "Software updates",
      "pricing.card2.item3": "Partner onboarding",
      "origin.eyebrow": "ORIGIN",
      "origin.title": "How did this project created",
      "origin.name": "Ruzgar",
      "origin.quote":
        "In that time, my wish was to buy a smart glass. Then I said to myself why don't I make a SmartCap. I was always thinking to earn money, then I started to do this project.",
      "origin.foot": "And then this project started...",
      "proto.eyebrow": "PROTOTYPE",
      "proto.title": "Currently in development",
      "proto.deadline": "The Smart Cap prototype is done by 18th of April.",
      "proto.desc": "Target milestone: April 18, 2026. We are finalizing hardware integration and AI calibration.",
      "proto.card.title": "Coming Soon",
      "proto.card.desc": "A premium wearable designed for investors, partners, and early adopters. Join us as we redefine intelligent fashion.",
      "proto.countdown.title": "Countdown to April 18, 2026",
      "proto.countdown.note": "Prototype completion milestone.",
      "proto.countdown.days": "Days",
      "proto.countdown.hours": "Hours",
      "proto.countdown.minutes": "Minutes",
      "proto.countdown.seconds": "Seconds",
      "vision.eyebrow": "VISION",
      "vision.title": "Future-forward by design",
      "vision.quote": "We aim to merge AI and fashion into one seamless experience.",
      "vision.desc":
        "RΔS Smartcap is engineered for a world where intelligence is elegant, unobtrusive, and always available. Our focus is on future-ready innovation, simplicity, and human-first design that feels premium from the first touch.",
      "contact.eyebrow": "CONTACT",
      "contact.title": "Let’s build the future together",
      "contact.desc": "Reach out for partnerships, pilots, or investor conversations.",
      "contact.emailLabel": "Email",
      "contact.cta": "Contact Us",
      "footer.tagline": "Wearable intelligence for a smarter tomorrow.",
      "footer.cta": "Partner With Us",
      "footer.audio": "Theme",
    },
    de: {
      "nav.features": "Funktionen",
      "nav.how": "So funktioniert es",
      "nav.use": "Anwendungsfalle",
      "nav.tech": "Technologie",
      "nav.readiness": "Reifegrad",
      "nav.roadmap": "Fahrplan",
      "nav.partners": "Partner",
      "nav.pricing": "Preis",
      "nav.origin": "Ursprung",
      "nav.prototype": "Prototyp",
      "nav.vision": "Vision",
      "nav.contact": "Kontakt",
      "strip.item1": "Umgebungsvision-Intelligenz",
      "strip.item2": "Echtzeit-Szenenverstandnis",
      "strip.item3": "Haptische Navigationshinweise",
      "strip.item4": "Voice-first Steuerung",
      "strip.item5": "Assistive Barrierefreiheits-Schicht",
      "strip.item6": "Sichere Cloud-Logik",
      "strip.item7": "Hands-free Ubersetzung",
      "strip.item8": "Bluetooth-Geratenetz",
      "hero.eyebrow": "KI-GESTUTZTE WEARABLE-INTELLIGENZ",
      "hero.title": "Die Zukunft der Wearable-KI",
      "hero.subtitle": "Lernen Sie RΔS Smartcap kennen",
      "hero.desc":
        "RΔS Smartcap vereint Kamerasicht, raumliches Audio und Cloud-KI in einem Premium-Wearable, das den Alltag mit Echtzeit-Kontext und Guidance erweitert.",
      "hero.tagline": "Nicht nur eine Technologie, sondern Wearable-Technologie",
      "hero.cta": "Die Zukunft erleben",
      "hero.ctaAlt": "Unsere Vision",
      "hero.metric1": "Kontextbewusstsein",
      "hero.metric2": "KI-Reaktionszeit",
      "hero.metric3": "Stetige Unterstutzung",
      "panel.subtitle": "Prototyp-Intelligenzschicht",
      "panel.spec.visionLabel": "Vision",
      "panel.spec.visionValue": "Echtzeit-Erfassung",
      "panel.spec.audioLabel": "Audio",
      "panel.spec.audioValue": "Richtungsfeedback",
      "panel.spec.connLabel": "Konnektivitat",
      "panel.spec.connValue": "Bluetooth + Cloud-KI",
      "panel.footer": "Entwickelt fur nahtlose Alltagserweiterung.",
      "features.eyebrow": "FUNKTIONEN",
      "features.title": "Fur intelligentes Leben designt",
      "features.desc": "Jede Komponente ist darauf ausgelegt, Ambient Intelligence ohne Reibung zu liefern.",
      "features.note": "Alle aufgefuhrten Funktionen sind in aktuellen Prototyp-Builds verfugbar.",
      "feature1.title": "KI-gestutzter Assistent",
      "feature1.desc": "Kontextbewusste Unterstutzung, die sich in Echtzeit an Ihren Tag anpasst.",
      "feature2.title": "Kamera fur Echtzeitanalyse",
      "feature2.desc": "Szenenverstandnis mit On-Device-Erfassung und Cloud-Vision.",
      "feature3.title": "Sprachinteraktion",
      "feature3.desc": "Hands-free Steuerung uber ein stets bereites Mikrofon-Array.",
      "feature4.title": "Bluetooth-Konnektivitat",
      "feature4.desc": "Nahtloses Pairing mit Smartphones, Earbuds und verbundenen Geraten.",
      "feature5.title": "Barrierefreiheit fur Sehbehinderte",
      "feature5.desc": "Vibrationsfeedback liefert dezente, gerichtete Fuhrung.",
      "feature.status": "Im Prototyp verfugbar",
      "how.eyebrow": "SO FUNKTIONIERT ES",
      "how.title": "Von der Erfassung zur Antwort in Sekunden",
      "how.step1.title": "Erfassen",
      "how.step1.desc": "Kamera und Mikrofon sammeln reale Eingaben um Sie herum.",
      "how.step2.title": "Verarbeiten",
      "how.step2.desc": "Cloud-KI interpretiert Kontext, Objekte und Intention sofort.",
      "how.step3.title": "Antworten",
      "how.step3.desc": "Audio-Feedback fuhrt Sie prazise zum nachsten Schritt.",
      "use.eyebrow": "ANWENDUNGSFALLE",
      "use.title": "Fur echte Wirkung gebaut",
      "use.case1.title": "Alltagshilfe",
      "use.case1.desc": "Erinnerungen, Objekterkennung und kontextuelle Hinweise.",
      "use.case2.title": "Barrierefreiheit",
      "use.case2.desc": "Mehr Unabhangigkeit fur sehbehinderte Nutzer.",
      "use.case3.title": "Reisen & Navigation",
      "use.case3.desc": "Schritt-fur-Schritt-Fuhrung mit raumlichem Bewusstsein.",
      "use.case4.title": "Smarte Kommunikation",
      "use.case4.desc": "Ubersetzen, transkribieren und verbinden ohne das Telefon zu nutzen.",
      "stack.eyebrow": "TECHNOLOGIE",
      "stack.title": "Ein Wearable-tauglicher Intelligenz-Stack",
      "stack.desc": "Entwickelt fur niedrige Latenz und Vertrauen im echten Alltag.",
      "stack.card1.title": "Sensor-Fusion Core",
      "stack.card1.desc": "Kamera-, Mikrofon- und Bewegungsdaten fur situatives Verstandnis.",
      "stack.card2.title": "Edge + Cloud KI",
      "stack.card2.desc": "Schnelles On-Device-Filtering mit skalierbarer Cloud-Intelligenz.",
      "stack.card3.title": "Spatial Feedback Engine",
      "stack.card3.desc": "Raumliches Audio und haptische Signale fur diskrete Fuhrung.",
      "readiness.eyebrow": "REIFEGRAD",
      "readiness.title": "Prototype-Reifegrad Dashboard",
      "readiness.desc": "Aktueller Build-Status uber Hardware, KI und nutzerzentrierte Tests.",
      "readiness.card1.title": "Hardware-Integration",
      "readiness.card1.desc": "Kamera, Mikrofonarray und Haptik im Prototyp validiert.",
      "readiness.card2.title": "KI-Kalibrierung",
      "readiness.card2.desc": "Kontextmodelle fur reale Nutzung abgestimmt.",
      "readiness.card3.title": "Nutzer-Validierung",
      "readiness.card3.desc": "Barrierefreiheits-Feedback und Pilottests laufen.",
      "readiness.card4.title": "Fertigungs-Reife",
      "readiness.card4.desc": "Lieferkettenpartner und Tooling fixiert.",
      "roadmap.eyebrow": "FAHRPLAN",
      "roadmap.title": "Ein klarer Weg zum Launch",
      "roadmap.desc": "Fokussierte Meilensteine vom Prototyp bis Pilot und Partner-Rollout.",
      "roadmap.step1.date": "18. April 2026",
      "roadmap.step1.title": "Prototyp abgeschlossen",
      "roadmap.step1.desc": "Kern-Hardware + KI-Integration finalisiert.",
      "roadmap.step2.date": "Q2 2026",
      "roadmap.step2.title": "Pilotprogramme",
      "roadmap.step2.desc": "Einsatz mit Barrierefreiheits-Partnern und Feldtests.",
      "roadmap.step3.date": "Q3 2026",
      "roadmap.step3.title": "Partner-Integrationen",
      "roadmap.step3.desc": "Sichere Plattform-Integrationen und Developer-Tools.",
      "roadmap.step4.date": "Q4 2026",
      "roadmap.step4.title": "Limitierter Launch",
      "roadmap.step4.desc": "Kuratiertes Rollout fur strategische Partner.",
      "partners.eyebrow": "PARTNER",
      "partners.title": "Fur Zusammenarbeit gebaut",
      "partners.desc": "Wir offnen eine begrenzte Partnerkohorte, um Wirkung im Alltag zu validieren.",
      "partners.card1.title": "Pilotprogramme",
      "partners.card1.desc": "Use Cases gemeinsam gestalten und in realen Umgebungen testen.",
      "partners.card2.title": "Integration Toolkit",
      "partners.card2.desc": "Anbindung an Ihre Plattformen mit sicheren Datenflussen.",
      "partners.card3.title": "Enterprise-Readiness",
      "partners.card3.desc": "Governance, Compliance und Support von Anfang an.",
      "partners.cta": "Partnerzugang anfragen",
      "proto.eyebrow": "PROTOTYP",
      "proto.title": "Derzeit in Entwicklung",
      "proto.deadline": "Der Smart Cap Prototyp ist bis zum 18. April fertig.",
      "proto.desc": "Zielmeilenstein: 18. April 2026. Wir finalisieren Hardware-Integration und KI-Kalibrierung.",
      "proto.card.title": "Demnachst verfugbar",
      "proto.card.desc": "Ein Premium-Wearable fur Investoren, Partner und Early Adopters. Seien Sie dabei, wenn wir intelligente Fashion neu definieren.",
      "proto.countdown.title": "Countdown bis 18. April 2026",
      "proto.countdown.note": "Meilenstein der Prototyp-Fertigstellung.",
      "proto.countdown.days": "Tage",
      "proto.countdown.hours": "Stunden",
      "proto.countdown.minutes": "Minuten",
      "proto.countdown.seconds": "Sekunden",
      "vision.eyebrow": "VISION",
      "vision.title": "Zukunftsorientiert designt",
      "vision.quote": "Wir wollen KI und Mode zu einem nahtlosen Erlebnis verbinden.",
      "vision.desc":
        "RΔS Smartcap ist fur eine Welt entwickelt, in der Intelligenz elegant, unaufdringlich und jederzeit verfugbar ist. Unser Fokus liegt auf zukunftsfahiger Innovation, Einfachheit und humanem Design, das sich vom ersten Moment an premium anfuhlt.",
      "footer.tagline": "Wearable-Intelligenz fur ein smarteres Morgen.",
      "footer.cta": "Partner werden",
    },
    tr: {
      "nav.features": "Ozellikler",
      "nav.how": "Nasil Calisir",
      "nav.use": "Kullanim Alanlari",
      "nav.tech": "Teknoloji",
      "nav.readiness": "Hazirlik",
      "nav.roadmap": "Yol Haritasi",
      "nav.partners": "Ortaklar",
      "nav.pricing": "Fiyatlar",
      "nav.origin": "Baslangic",
      "nav.prototype": "Prototip",
      "nav.vision": "Vizyon",
      "nav.contact": "Iletisim",
      "strip.item1": "Ortam gorusu zekasi",
      "strip.item2": "Gercek zamanli sahne anlama",
      "strip.item3": "Haptik navigasyon ipuclari",
      "strip.item4": "Ses-oncelikli kontrol",
      "strip.item5": "Erisilebilirlik destek katmani",
      "strip.item6": "Guvenli bulut akil yurutme",
      "strip.item7": "Eller serbest ceviri",
      "strip.item8": "Bluetooth cihaz agi",
      "hero.eyebrow": "YAPAY ZEKA DESTEKLI WEARABLE ZEKASI",
      "hero.title": "Giyilebilir Yapay Zekanin Gelecegi",
      "hero.subtitle": "RΔS Smartcap ile tanisin",
      "hero.desc":
        "RΔS Smartcap, kamera gorusu, mekansal ses ve bulut yapay zekayi tek bir premium giyilebilir urunde birlestirir ve gunluk yasami gercek zamanli baglam ve rehberlikle guclendirir.",
      "hero.tagline": "Sadece bir teknoloji degil, giyilebilir teknolojidir",
      "hero.cta": "Gelecegi Kesfet",
      "hero.ctaAlt": "Vizyonumuz",
      "hero.metric1": "Baglam Farkindaligi",
      "hero.metric2": "Yapay Zeka Tepki Suresi",
      "hero.metric3": "Her An Destek",
      "panel.subtitle": "Prototip Zeka Katmani",
      "panel.spec.visionLabel": "Gorus",
      "panel.spec.visionValue": "Gercek zamanli yakalama",
      "panel.spec.audioLabel": "Ses",
      "panel.spec.audioValue": "Yonlu geri bildirim",
      "panel.spec.connLabel": "Baglanti",
      "panel.spec.connValue": "Bluetooth + Bulut AI",
      "panel.footer": "Gunluk yasam icin kesintisiz destek tasarimi.",
      "features.eyebrow": "OZELLIKLER",
      "features.title": "Akilli yasam icin tasarlandi",
      "features.desc": "Her bilesen, surtunmesiz ambient zeka sunmak icin amaca yonelik.",
      "features.note": "Listelenen tum ozellikler mevcut prototiplerde kullanilabilir.",
      "feature1.title": "Yapay zeka destekli asistan",
      "feature1.desc": "Gunluk hayata gercek zamanli uyum saglayan baglam odakli destek.",
      "feature2.title": "Gercek zamanli analiz icin kamera",
      "feature2.desc": "Cihaz ustu yakalama ve bulut gorusu ile sahne anlama.",
      "feature3.title": "Sesli etkilesim",
      "feature3.desc": "Her zaman hazir mikrofon dizisi ile eller serbest kontrol.",
      "feature4.title": "Bluetooth baglantisi",
      "feature4.desc": "Telefon, kulaklik ve bagli cihazlarla sorunsuz eslesme.",
      "feature5.title": "Gorme engelliler icin erisilebilirlik",
      "feature5.desc": "Titreşim geri bildirimiyle gizli ve yonlu rehberlik.",
      "feature.status": "Prototipte mevcut",
      "how.eyebrow": "NASIL CALISIR",
      "how.title": "Yakalamadan cevaba saniyeler icinde",
      "how.step1.title": "Yakala",
      "how.step1.desc": "Kamera ve mikrofon cevredeki girdileri toplar.",
      "how.step2.title": "Isle",
      "how.step2.desc": "Bulut yapay zeka baglami ve niyeti aninda yorumlar.",
      "how.step3.title": "Yanıtla",
      "how.step3.desc": "Sesli geri bildirim sonraki adimi netlestirir.",
      "use.eyebrow": "KULLANIM ALANLARI",
      "use.title": "Gercek dunya etkisi icin",
      "use.case1.title": "Gunluk yasam destegi",
      "use.case1.desc": "Hatirlatmalar, nesne tanima ve baglamsal ipuclari.",
      "use.case2.title": "Erisilebilirlik",
      "use.case2.desc": "Gorme engelli kullanicilar icin daha fazla bagimsizlik.",
      "use.case3.title": "Seyahat ve navigasyon",
      "use.case3.desc": "Mekansal farkindalikla adim adim yonlendirme.",
      "use.case4.title": "Akilli iletisim",
      "use.case4.desc": "Telefonu elinize almadan ceviri ve transkripsiyon.",
      "stack.eyebrow": "TEKNOLOJI",
      "stack.title": "Giyilebilir seviye zeka altyapisi",
      "stack.desc": "Gercek dunyada dusuk gecikme ve guven icin tasarlandi.",
      "stack.card1.title": "Sensor Birlesim Cekirdegi",
      "stack.card1.desc": "Kamera, mikrofon ve hareket verileriyle durumsal farkindalik.",
      "stack.card2.title": "Edge + Bulut AI",
      "stack.card2.desc": "Cihaz ustu hizli filtreleme ve olceklenebilir bulut zekasi.",
      "stack.card3.title": "Mekansal Geri Bildirim",
      "stack.card3.desc": "Gizli yonlendirme icin yonlu ses ve haptik ipuclari.",
      "readiness.eyebrow": "HAZIRLIK",
      "readiness.title": "Prototip hazirlik paneli",
      "readiness.desc": "Donanim, AI ve insan odakli testlerde guncel durum.",
      "readiness.card1.title": "Donanim entegrasyonu",
      "readiness.card1.desc": "Kamera, mikrofon dizisi ve haptikler prototipte dogrulandi.",
      "readiness.card2.title": "AI kalibrasyonu",
      "readiness.card2.desc": "Baglam modelleri gercek dunya kullanimina ayarlandi.",
      "readiness.card3.title": "Kullanici dogrulama",
      "readiness.card3.desc": "Erisilebilirlik geri bildirimi ve pilot testler suruyor.",
      "readiness.card4.title": "Uretim hazirligi",
      "readiness.card4.desc": "Tedarik zinciri ortaklari ve kaliplar netlesti.",
      "roadmap.eyebrow": "YOL HARITASI",
      "roadmap.title": "Lansman icin net yol",
      "roadmap.desc": "Prototipten pilote ve partner kurulumuna odakli adimlar.",
      "roadmap.step1.date": "18 Nisan 2026",
      "roadmap.step1.title": "Prototip tamam",
      "roadmap.step1.desc": "Temel donanim + AI entegrasyonu tamamlandi.",
      "roadmap.step2.date": "Q2 2026",
      "roadmap.step2.title": "Pilot programlar",
      "roadmap.step2.desc": "Erisilebilirlik ortaklariyla saha testleri.",
      "roadmap.step3.date": "Q3 2026",
      "roadmap.step3.title": "Partner entegrasyonlari",
      "roadmap.step3.desc": "Guvenli platform entegrasyonlari ve gelistirici araclari.",
      "roadmap.step4.date": "Q4 2026",
      "roadmap.step4.title": "Sinirli lansman",
      "roadmap.step4.desc": "Stratejik partnerler icin secili rollout.",
      "partners.eyebrow": "ORTAKLAR",
      "partners.title": "Is birligi icin tasarlandi",
      "partners.desc": "Gercek dunya etkisini dogrulamak icin sinirli partner kohortu aciyoruz.",
      "partners.card1.title": "Pilot Programlar",
      "partners.card1.desc": "Kullanim senaryolarini birlikte tasarlayip sahada test edin.",
      "partners.card2.title": "Entegrasyon Araclari",
      "partners.card2.desc": "Guvenli veri akislariyla platformlariniza baglanin.",
      "partners.card3.title": "Kurumsal Hazirlik",
      "partners.card3.desc": "Yonetisim, uyumluluk ve destek basta planli.",
      "partners.cta": "Ortaklik Talebi",
      "proto.eyebrow": "PROTOTIP",
      "proto.title": "Su anda gelistirilmekte",
      "proto.deadline": "Smart Cap prototipi 18 Nisan'a kadar tamamlanir.",
      "proto.desc": "Hedef kilometre tasi: 18 Nisan 2026. Donanim entegrasyonu ve AI kalibrasyonu tamamlanmak uzere.",
      "proto.card.title": "Yakinda",
      "proto.card.desc": "Yatirimcilar, ortaklar ve erken benimseyenler icin premium giyilebilir cihaz. Akilli modayi yeniden tanimlamak icin bize katilin.",
      "proto.countdown.title": "18 Nisan 2026'ya geri sayim",
      "proto.countdown.note": "Prototip tamamlanma kilometre tasi.",
      "proto.countdown.days": "Gun",
      "proto.countdown.hours": "Saat",
      "proto.countdown.minutes": "Dakika",
      "proto.countdown.seconds": "Saniye",
      "vision.eyebrow": "VIZYON",
      "vision.title": "Gelecege donuk tasarim",
      "vision.quote": "Yapay zekayi ve modayi tek bir sorunsuz deneyimde birlestirmeyi hedefliyoruz.",
      "vision.desc":
        "RΔS Smartcap, zekanin zarif, dikkat cekmeyen ve her an erisilebilir oldugu bir dunya icin tasarlandi. Odak noktamiz, gelecege hazir inovasyon, sadelik ve insan odakli premium tasarimdir.",
      "footer.tagline": "Daha akilli bir yarin icin giyilebilir zeka.",
      "footer.cta": "Ortak Olun",
    },
    fr: {
      "nav.features": "Fonctionnalites",
      "nav.how": "Fonctionnement",
      "nav.use": "Cas d'utilisation",
      "nav.tech": "Technologie",
      "nav.readiness": "Preparation",
      "nav.roadmap": "Feuille de route",
      "nav.partners": "Partenaires",
      "nav.pricing": "Tarifs",
      "nav.origin": "Origine",
      "nav.prototype": "Prototype",
      "nav.vision": "Vision",
      "nav.contact": "Contact",
      "strip.item1": "Intelligence vision ambiante",
      "strip.item2": "Comprehension de scene en temps reel",
      "strip.item3": "Indications haptiques de navigation",
      "strip.item4": "Controle vocal prioritaire",
      "strip.item5": "Couche d'accessibilite assistive",
      "strip.item6": "Raisonnement cloud securise",
      "strip.item7": "Traduction mains libres",
      "strip.item8": "Reseau d'appareils Bluetooth",
      "hero.eyebrow": "INTELLIGENCE WEARABLE ALIMENTEE PAR IA",
      "hero.title": "Le futur de l'IA portable",
      "hero.subtitle": "Decouvrez RΔS Smartcap",
      "hero.desc":
        "RΔS Smartcap combine vision camera, audio spatial et IA cloud dans un wearable premium qui renforce le quotidien avec du contexte en temps reel.",
      "hero.tagline": "Pas seulement une technologie, mais une technologie portable",
      "hero.cta": "Explorer le futur",
      "hero.ctaAlt": "Notre vision",
      "hero.metric1": "Conscience du contexte",
      "hero.metric2": "Temps de reponse IA",
      "hero.metric3": "Assistance continue",
      "panel.subtitle": "Couche d'intelligence prototype",
      "panel.spec.visionLabel": "Vision",
      "panel.spec.visionValue": "Capture en temps reel",
      "panel.spec.audioLabel": "Audio",
      "panel.spec.audioValue": "Retour directionnel",
      "panel.spec.connLabel": "Connectivite",
      "panel.spec.connValue": "Bluetooth + IA cloud",
      "panel.footer": "Concu pour une augmentation quotidienne fluide.",
      "features.eyebrow": "FONCTIONNALITES",
      "features.title": "Concu pour une vie intelligente",
      "features.desc": "Chaque composant est pense pour offrir une intelligence ambiante sans friction.",
      "features.note": "Toutes les fonctionnalites listees sont disponibles dans les prototypes actuels.",
      "feature1.title": "Assistant alimente par l'IA",
      "feature1.desc": "Un support contextuel qui s'adapte a votre journee en temps reel.",
      "feature2.title": "Camera pour analyse en temps reel",
      "feature2.desc": "Compréhension des scenes avec capture locale et vision cloud.",
      "feature3.title": "Interaction vocale",
      "feature3.desc": "Controle mains libres via un micro toujours pret.",
      "feature4.title": "Connectivite Bluetooth",
      "feature4.desc": "Appairage fluide avec telephones, ecouteurs et appareils connectes.",
      "feature5.title": "Accessibilite pour malvoyants",
      "feature5.desc": "Retour haptique discret pour un guidage directionnel.",
      "feature.status": "Disponible en prototype",
      "how.eyebrow": "FONCTIONNEMENT",
      "how.title": "De la capture a la reponse en quelques secondes",
      "how.step1.title": "Capturer",
      "how.step1.desc": "Camera et micro recueillent les signaux du monde reel.",
      "how.step2.title": "Traiter",
      "how.step2.desc": "L'IA cloud interprete le contexte et l'intention instantanement.",
      "how.step3.title": "Repondre",
      "how.step3.desc": "Le retour audio guide la prochaine action avec precision.",
      "use.eyebrow": "CAS D'UTILISATION",
      "use.title": "Concu pour un impact reel",
      "use.case1.title": "Assistance quotidienne",
      "use.case1.desc": "Rappels, reconnaissance d'objets et conseils contextuels.",
      "use.case2.title": "Accessibilite",
      "use.case2.desc": "Plus d'autonomie pour les personnes malvoyantes.",
      "use.case3.title": "Voyage et navigation",
      "use.case3.desc": "Guidage pas a pas avec alertes spatiales.",
      "use.case4.title": "Communication intelligente",
      "use.case4.desc": "Traduire, transcrire et se connecter sans sortir le telephone.",
      "stack.eyebrow": "TECHNOLOGIE",
      "stack.title": "Une pile d'intelligence de niveau wearable",
      "stack.desc": "Concue pour une faible latence et une grande fiabilite.",
      "stack.card1.title": "Noyau de fusion des capteurs",
      "stack.card1.desc": "Camera, micro et mouvements combines pour la conscience situationnelle.",
      "stack.card2.title": "Edge + IA cloud",
      "stack.card2.desc": "Filtrage rapide sur l'appareil et raisonnement cloud evolutif.",
      "stack.card3.title": "Moteur de retour spatial",
      "stack.card3.desc": "Audio directionnel et haptique pour un guidage discret.",
      "readiness.eyebrow": "PREPARATION",
      "readiness.title": "Tableau de preparation du prototype",
      "readiness.desc": "Etat actuel du build sur le materiel, l'IA et les tests humains.",
      "readiness.card1.title": "Integration materielle",
      "readiness.card1.desc": "Camera, micro et haptique valides dans le prototype.",
      "readiness.card2.title": "Calibration IA",
      "readiness.card2.desc": "Modeles de contexte ajustes pour l'usage reel.",
      "readiness.card3.title": "Validation utilisateur",
      "readiness.card3.desc": "Retours accessibilite et tests pilotes en cours.",
      "readiness.card4.title": "Preparation fabrication",
      "readiness.card4.desc": "Partenaires supply chain et outillages verrouilles.",
      "roadmap.eyebrow": "FEUILLE DE ROUTE",
      "roadmap.title": "Une trajectoire claire vers le lancement",
      "roadmap.desc": "Etapes concentrees du prototype au pilote et aux partenaires.",
      "roadmap.step1.date": "18 avril 2026",
      "roadmap.step1.title": "Prototype termine",
      "roadmap.step1.desc": "Integration hardware + IA finalisee.",
      "roadmap.step2.date": "T2 2026",
      "roadmap.step2.title": "Programmes pilotes",
      "roadmap.step2.desc": "Deploiement avec partenaires accessibilite et tests terrain.",
      "roadmap.step3.date": "T3 2026",
      "roadmap.step3.title": "Integrations partenaires",
      "roadmap.step3.desc": "Integrations plateformes securisees et outils developpeurs.",
      "roadmap.step4.date": "T4 2026",
      "roadmap.step4.title": "Lancement limite",
      "roadmap.step4.desc": "Deploiement selectif pour partenaires strategiques.",
      "partners.eyebrow": "PARTENAIRES",
      "partners.title": "Concu pour la collaboration",
      "partners.desc": "Nous ouvrons un cohort de partenaires limite pour valider l'impact terrain.",
      "partners.card1.title": "Programmes pilotes",
      "partners.card1.desc": "Co-concevoir des cas d'usage et tester en conditions reelles.",
      "partners.card2.title": "Kit d'integration",
      "partners.card2.desc": "Connectez vos plateformes avec des flux de donnees securises.",
      "partners.card3.title": "Preparation entreprise",
      "partners.card3.desc": "Gouvernance, conformite et support integres.",
      "partners.cta": "Demander l'acces partenaire",
      "proto.eyebrow": "PROTOTYPE",
      "proto.title": "Actuellement en developpement",
      "proto.deadline": "Le prototype Smart Cap est pret avant le 18 avril.",
      "proto.desc": "Objectif: 18 avril 2026. Integration materielle et calibration IA en cours.",
      "proto.card.title": "Bientot disponible",
      "proto.card.desc": "Un wearable premium pour investisseurs, partenaires et early adopters. Rejoignez-nous pour redefinir la mode intelligente.",
      "proto.countdown.title": "Compte a rebours jusqu'au 18 avril 2026",
      "proto.countdown.note": "Jalon de finalisation du prototype.",
      "proto.countdown.days": "Jours",
      "proto.countdown.hours": "Heures",
      "proto.countdown.minutes": "Minutes",
      "proto.countdown.seconds": "Secondes",
      "vision.eyebrow": "VISION",
      "vision.title": "Concu pour l'avenir",
      "vision.quote": "Nous voulons fusionner l'IA et la mode en une experience fluide.",
      "vision.desc":
        "RΔS Smartcap est concu pour un monde ou l'intelligence est elegante, discrete et toujours disponible. Notre objectif: innovation future-ready, simplicite et design humain premium.",
      "footer.tagline": "Une intelligence wearable pour un futur plus intelligent.",
      "footer.cta": "Devenir partenaire",
    },
    it: {
      "nav.features": "Funzionalita",
      "nav.how": "Come Funziona",
      "nav.use": "Casi d'uso",
      "nav.tech": "Tecnologia",
      "nav.readiness": "Prontezza",
      "nav.roadmap": "Roadmap",
      "nav.partners": "Partner",
      "nav.pricing": "Prezzi",
      "nav.origin": "Origine",
      "nav.prototype": "Prototipo",
      "nav.vision": "Visione",
      "nav.contact": "Contatto",
      "strip.item1": "Intelligenza di visione ambientale",
      "strip.item2": "Comprensione scena in tempo reale",
      "strip.item3": "Segnali aptici di navigazione",
      "strip.item4": "Controllo voice-first",
      "strip.item5": "Layer di accessibilita assistiva",
      "strip.item6": "Ragionamento cloud sicuro",
      "strip.item7": "Traduzione hands-free",
      "strip.item8": "Mesh di dispositivi Bluetooth",
      "hero.eyebrow": "INTELLIGENZA WEARABLE ALIMENTATA DA IA",
      "hero.title": "Il futuro dell'AI indossabile",
      "hero.subtitle": "Scopri RΔS Smartcap",
      "hero.desc":
        "RΔS Smartcap unisce visione camera, audio spaziale e IA cloud in un wearable premium che migliora la vita quotidiana con contesto in tempo reale.",
      "hero.tagline": "Non solo una tecnologia, ma tecnologia indossabile",
      "hero.cta": "Esplora il futuro",
      "hero.ctaAlt": "La nostra visione",
      "hero.metric1": "Consapevolezza del contesto",
      "hero.metric2": "Tempo di risposta IA",
      "hero.metric3": "Assistenza continua",
      "panel.subtitle": "Livello di intelligenza prototipo",
      "panel.spec.visionLabel": "Visione",
      "panel.spec.visionValue": "Acquisizione in tempo reale",
      "panel.spec.audioLabel": "Audio",
      "panel.spec.audioValue": "Feedback direzionale",
      "panel.spec.connLabel": "Connettivita",
      "panel.spec.connValue": "Bluetooth + IA cloud",
      "panel.footer": "Progettato per un potenziamento quotidiano senza attriti.",
      "features.eyebrow": "FUNZIONALITA",
      "features.title": "Progettato per una vita intelligente",
      "features.desc": "Ogni componente e pensato per fornire intelligenza ambientale senza attrito.",
      "features.note": "Tutte le funzionalita elencate sono disponibili nei prototipi attuali.",
      "feature1.title": "Assistente alimentato da IA",
      "feature1.desc": "Supporto contestuale che si adatta alla tua giornata in tempo reale.",
      "feature2.title": "Camera per analisi in tempo reale",
      "feature2.desc": "Comprensione della scena con acquisizione locale e visione cloud.",
      "feature3.title": "Interazione vocale",
      "feature3.desc": "Controllo hands-free grazie a un array microfonico sempre attivo.",
      "feature4.title": "Connettivita Bluetooth",
      "feature4.desc": "Abbinamento fluido con telefoni, auricolari e dispositivi connessi.",
      "feature5.title": "Accessibilita per non vedenti",
      "feature5.desc": "Feedback aptico discreto per un orientamento direzionale.",
      "feature.status": "Disponibile nel prototipo",
      "how.eyebrow": "COME FUNZIONA",
      "how.title": "Dalla cattura alla risposta in pochi secondi",
      "how.step1.title": "Cattura",
      "how.step1.desc": "Camera e microfono raccolgono input dal mondo reale.",
      "how.step2.title": "Elabora",
      "how.step2.desc": "L'IA cloud interpreta contesto, oggetti e intento all'istante.",
      "how.step3.title": "Rispondi",
      "how.step3.desc": "Il feedback audio guida il prossimo passo con precisione.",
      "use.eyebrow": "CASI D'USO",
      "use.title": "Progettato per un impatto reale",
      "use.case1.title": "Assistenza quotidiana",
      "use.case1.desc": "Promemoria, riconoscimento oggetti e suggerimenti contestuali.",
      "use.case2.title": "Accessibilita",
      "use.case2.desc": "Maggiore indipendenza per utenti non vedenti.",
      "use.case3.title": "Viaggi e navigazione",
      "use.case3.desc": "Guida passo passo con consapevolezza spaziale.",
      "use.case4.title": "Comunicazione smart",
      "use.case4.desc": "Traduci, trascrivi e connettiti senza prendere il telefono.",
      "stack.eyebrow": "TECNOLOGIA",
      "stack.title": "Uno stack di intelligenza per wearable",
      "stack.desc": "Progettato per bassa latenza e alta fiducia nel mondo reale.",
      "stack.card1.title": "Core di fusione sensoriale",
      "stack.card1.desc": "Camera, microfono e dati di movimento per consapevolezza situazionale.",
      "stack.card2.title": "Edge + IA cloud",
      "stack.card2.desc": "Filtraggio rapido on-device e ragionamento cloud scalabile.",
      "stack.card3.title": "Motore di feedback spaziale",
      "stack.card3.desc": "Audio direzionale e segnali aptici per una guida discreta.",
      "readiness.eyebrow": "PRONTEZZA",
      "readiness.title": "Dashboard di prontezza del prototipo",
      "readiness.desc": "Stato attuale su hardware, AI e test centrati sulle persone.",
      "readiness.card1.title": "Integrazione hardware",
      "readiness.card1.desc": "Camera, array microfonico e aptica validati nel prototipo.",
      "readiness.card2.title": "Calibrazione AI",
      "readiness.card2.desc": "Modelli di contesto ottimizzati per uso reale.",
      "readiness.card3.title": "Validazione utenti",
      "readiness.card3.desc": "Feedback accessibilita e test pilota in corso.",
      "readiness.card4.title": "Prontezza produzione",
      "readiness.card4.desc": "Partner supply chain e tooling definiti.",
      "roadmap.eyebrow": "ROADMAP",
      "roadmap.title": "Percorso chiaro verso il lancio",
      "roadmap.desc": "Traguardi dal prototipo al pilot e ai partner.",
      "roadmap.step1.date": "18 aprile 2026",
      "roadmap.step1.title": "Prototipo completo",
      "roadmap.step1.desc": "Integrazione hardware + AI completata.",
      "roadmap.step2.date": "Q2 2026",
      "roadmap.step2.title": "Programmi pilota",
      "roadmap.step2.desc": "Distribuzione con partner accessibilita e test sul campo.",
      "roadmap.step3.date": "Q3 2026",
      "roadmap.step3.title": "Integrazioni partner",
      "roadmap.step3.desc": "Integrazioni piattaforme sicure e strumenti developer.",
      "roadmap.step4.date": "Q4 2026",
      "roadmap.step4.title": "Rilascio limitato",
      "roadmap.step4.desc": "Rollout selettivo per partner strategici.",
      "partners.eyebrow": "PARTNER",
      "partners.title": "Costruito per la collaborazione",
      "partners.desc": "Apriamo una coorte limitata di partner per validare l'impatto sul campo.",
      "partners.card1.title": "Programmi pilota",
      "partners.card1.desc": "Co-progetta casi d'uso e testa in ambienti reali.",
      "partners.card2.title": "Toolkit di integrazione",
      "partners.card2.desc": "Collega le tue piattaforme con flussi dati sicuri.",
      "partners.card3.title": "Prontezza enterprise",
      "partners.card3.desc": "Governance, conformita e supporto integrati.",
      "partners.cta": "Richiedi accesso partner",
      "proto.eyebrow": "PROTOTIPO",
      "proto.title": "Attualmente in sviluppo",
      "proto.deadline": "Il prototipo Smart Cap sara pronto entro il 18 aprile.",
      "proto.desc": "Obiettivo: 18 aprile 2026. Integrazione hardware e calibrazione IA in corso.",
      "proto.card.title": "In arrivo",
      "proto.card.desc": "Un wearable premium per investitori, partner ed early adopters. Unisciti a noi per ridefinire la moda intelligente.",
      "proto.countdown.title": "Conto alla rovescia fino al 18 aprile 2026",
      "proto.countdown.note": "Traguardo di completamento del prototipo.",
      "proto.countdown.days": "Giorni",
      "proto.countdown.hours": "Ore",
      "proto.countdown.minutes": "Minuti",
      "proto.countdown.seconds": "Secondi",
      "vision.eyebrow": "VISIONE",
      "vision.title": "Design orientato al futuro",
      "vision.quote": "Puntiamo a unire IA e moda in un'unica esperienza fluida.",
      "vision.desc":
        "RΔS Smartcap e pensato per un mondo in cui l'intelligenza e elegante, discreta e sempre disponibile. Il nostro focus: innovazione futura, semplicita e design umano premium.",
      "footer.tagline": "Intelligenza wearable per un domani piu smart.",
      "footer.cta": "Diventa partner",
    },
    nl: {
      "nav.features": "Functies",
      "nav.how": "Hoe het werkt",
      "nav.use": "Toepassingen",
      "nav.tech": "Technologie",
      "nav.readiness": "Gereedheid",
      "nav.roadmap": "Roadmap",
      "nav.partners": "Partners",
      "nav.pricing": "Prijzen",
      "nav.origin": "Oorsprong",
      "nav.prototype": "Prototype",
      "nav.vision": "Visie",
      "nav.contact": "Contact",
      "strip.item1": "Omgevingsvisie-intelligentie",
      "strip.item2": "Realtime scene begrip",
      "strip.item3": "Haptische navigatie cues",
      "strip.item4": "Voice-first bediening",
      "strip.item5": "Toegankelijkheidslaag",
      "strip.item6": "Veilige cloud redenering",
      "strip.item7": "Hands-free vertaling",
      "strip.item8": "Bluetooth apparaten mesh",
      "hero.eyebrow": "AI-GEDREVEN WEARABLE-INTELLIGENTIE",
      "hero.title": "De toekomst van wearable AI",
      "hero.subtitle": "Maak kennis met RΔS Smartcap",
      "hero.desc":
        "RΔS Smartcap combineert cameravisie, ruimtelijke audio en cloud-AI in een premium wearable die het dagelijks leven versterkt met realtime context en begeleiding.",
      "hero.tagline": "Niet alleen technologie, maar draagbare technologie",
      "hero.cta": "Ontdek de toekomst",
      "hero.ctaAlt": "Onze visie",
      "hero.metric1": "Contextbewustzijn",
      "hero.metric2": "AI-responstijd",
      "hero.metric3": "Altijd beschikbaar",
      "panel.subtitle": "Prototype-intelligentielaag",
      "panel.spec.visionLabel": "Visie",
      "panel.spec.visionValue": "Realtime capture",
      "panel.spec.audioLabel": "Audio",
      "panel.spec.audioValue": "Richtingsfeedback",
      "panel.spec.connLabel": "Connectiviteit",
      "panel.spec.connValue": "Bluetooth + Cloud AI",
      "panel.footer": "Ontworpen voor naadloze dagelijkse ondersteuning.",
      "features.eyebrow": "FUNCTIES",
      "features.title": "Ontworpen voor intelligent leven",
      "features.desc": "Elke component is gebouwd om ambient intelligence zonder frictie te leveren.",
      "features.note": "Alle genoemde functies zijn beschikbaar in huidige prototype-builds.",
      "feature1.title": "AI-gestuurde assistent",
      "feature1.desc": "Contextbewuste ondersteuning die zich realtime aanpast aan je dag.",
      "feature2.title": "Camera voor realtime analyse",
      "feature2.desc": "Scenebegrip met on-device capture en cloud vision.",
      "feature3.title": "Spraakinteractie",
      "feature3.desc": "Hands-free bediening via een altijd klaar microfoonarray.",
      "feature4.title": "Bluetooth-connectiviteit",
      "feature4.desc": "Naadloze koppeling met telefoons, earbuds en verbonden apparaten.",
      "feature5.title": "Toegankelijkheid voor slechtzienden",
      "feature5.desc": "Trillingsfeedback zorgt voor discrete, gerichte begeleiding.",
      "feature.status": "Beschikbaar in prototype",
      "how.eyebrow": "HOE HET WERKT",
      "how.title": "Van capture naar response in seconden",
      "how.step1.title": "Vastleggen",
      "how.step1.desc": "Camera en microfoon verzamelen inputs uit de echte wereld.",
      "how.step2.title": "Verwerken",
      "how.step2.desc": "Cloud-AI interpreteert context, objecten en intenties direct.",
      "how.step3.title": "Reageren",
      "how.step3.desc": "Audiofeedback begeleidt de volgende stap met precisie.",
      "use.eyebrow": "TOEPASSINGEN",
      "use.title": "Gebouwd voor echte impact",
      "use.case1.title": "Dagelijkse assistentie",
      "use.case1.desc": "Herinneringen, objectherkenning en contextuele prompts.",
      "use.case2.title": "Toegankelijkheid",
      "use.case2.desc": "Meer onafhankelijkheid voor slechtziende gebruikers.",
      "use.case3.title": "Reizen en navigatie",
      "use.case3.desc": "Stap-voor-stap begeleiding met ruimtelijk bewustzijn.",
      "use.case4.title": "Slimme communicatie",
      "use.case4.desc": "Vertalen, transcriberen en verbinden zonder je telefoon te pakken.",
      "stack.eyebrow": "TECHNOLOGIE",
      "stack.title": "Een wearable-grade intelligentiestack",
      "stack.desc": "Ontworpen voor lage latency en hoog vertrouwen in de echte wereld.",
      "stack.card1.title": "Sensorfusie-kern",
      "stack.card1.desc": "Camera-, microfoon- en bewegingsdata voor situationeel bewustzijn.",
      "stack.card2.title": "Edge + Cloud AI",
      "stack.card2.desc": "Snelle filtering op het apparaat en schaalbare cloud-intelligentie.",
      "stack.card3.title": "Ruimtelijke feedback engine",
      "stack.card3.desc": "Directionele audio en haptische cues voor discrete begeleiding.",
      "readiness.eyebrow": "GEREEDHEID",
      "readiness.title": "Prototype gereedheid dashboard",
      "readiness.desc": "Huidige buildstatus voor hardware, AI en mensgerichte tests.",
      "readiness.card1.title": "Hardware integratie",
      "readiness.card1.desc": "Camera, microfoonarray en haptiek gevalideerd in prototype.",
      "readiness.card2.title": "AI calibratie",
      "readiness.card2.desc": "Contextmodellen afgestemd op echt gebruik.",
      "readiness.card3.title": "Gebruikersvalidatie",
      "readiness.card3.desc": "Toegankelijkheidsfeedback en pilots lopen.",
      "readiness.card4.title": "Productie gereedheid",
      "readiness.card4.desc": "Supply chain partners en tooling vastgelegd.",
      "roadmap.eyebrow": "ROADMAP",
      "roadmap.title": "Heldere route naar lancering",
      "roadmap.desc": "Gerichte mijlpalen van prototype naar pilot en partner deployment.",
      "roadmap.step1.date": "18 april 2026",
      "roadmap.step1.title": "Prototype voltooid",
      "roadmap.step1.desc": "Kernhardware + AI integratie afgerond.",
      "roadmap.step2.date": "Q2 2026",
      "roadmap.step2.title": "Pilotprogramma's",
      "roadmap.step2.desc": "Uitrol met toegankelijkheidspartners en veldtests.",
      "roadmap.step3.date": "Q3 2026",
      "roadmap.step3.title": "Partner integraties",
      "roadmap.step3.desc": "Veilige platform integraties en developer tooling.",
      "roadmap.step4.date": "Q4 2026",
      "roadmap.step4.title": "Beperkte release",
      "roadmap.step4.desc": "Geselecteerde rollout voor strategische partners.",
      "partners.eyebrow": "PARTNERS",
      "partners.title": "Gebouwd voor samenwerking",
      "partners.desc": "We openen een beperkte partnercohort om impact in de praktijk te valideren.",
      "partners.card1.title": "Pilotprogramma's",
      "partners.card1.desc": "Co-ontwerp use cases en test in echte omgevingen.",
      "partners.card2.title": "Integratietoolkit",
      "partners.card2.desc": "Verbind met je platformen via veilige datastromen.",
      "partners.card3.title": "Enterprise-gereed",
      "partners.card3.desc": "Governance, compliance en support standaard ingebouwd.",
      "partners.cta": "Partner toegang aanvragen",
      "proto.eyebrow": "PROTOTYPE",
      "proto.title": "Momenteel in ontwikkeling",
      "proto.deadline": "De Smart Cap prototype is klaar voor 18 april.",
      "proto.desc": "Doelmijlpaal: 18 april 2026. Hardware-integratie en AI-kalibratie worden afgerond.",
      "proto.card.title": "Binnenkort",
      "proto.card.desc": "Een premium wearable voor investeerders, partners en early adopters. Doe mee en herdefinieer slimme fashion.",
      "proto.countdown.title": "Countdown tot 18 april 2026",
      "proto.countdown.note": "Prototype-opleveringsmijlpaal.",
      "proto.countdown.days": "Dagen",
      "proto.countdown.hours": "Uren",
      "proto.countdown.minutes": "Minuten",
      "proto.countdown.seconds": "Seconden",
      "vision.eyebrow": "VISIE",
      "vision.title": "Toekomstgericht design",
      "vision.quote": "We willen AI en fashion samenbrengen in een naadloze ervaring.",
      "vision.desc":
        "RΔS Smartcap is ontworpen voor een wereld waarin intelligentie elegant, onopvallend en altijd beschikbaar is. Onze focus: future-ready innovatie, eenvoud en mensgericht premium design.",
      "footer.tagline": "Wearable intelligentie voor een slimmere morgen.",
      "footer.cta": "Word partner",
    },
  };

  const i18nElements = Array.from(document.querySelectorAll("[data-i18n]"));

  let currentLang = "en";

  function applyLanguage(lang) {
    const dict = translations[lang] || translations.en;
    i18nElements.forEach((el) => {
      const key = el.dataset.i18n;
      const value = dict[key] ?? translations.en[key];
      if (value) {
        el.textContent = value;
      }
    });

    document.documentElement.lang = lang;
    document.querySelectorAll(".lang-switcher .lang").forEach((btn) => {
      btn.classList.toggle("active", btn.dataset.lang === lang);
    });

    currentLang = lang;
    localStorage.setItem("ras-lang", lang);
  }

  const savedLang = localStorage.getItem("ras-lang");
  const initialLang = savedLang && translations[savedLang] ? savedLang : "en";
  applyLanguage(initialLang);

  document.querySelectorAll(".lang-switcher .lang").forEach((button) => {
    button.addEventListener("click", () => {
      const lang = button.dataset.lang;
      if (lang) {
        applyLanguage(lang);
      }
    });
  });

  const countdownTargets = document.querySelectorAll(".countdown");

  function formatTime(value) {
    return String(value).padStart(2, "0");
  }

  function setupCountdown(container) {
    const daysEl = container.querySelector("#days");
    const hoursEl = container.querySelector("#hours");
    const minutesEl = container.querySelector("#minutes");
    const secondsEl = container.querySelector("#seconds");
    const noteEl = container.querySelector(".countdown-note");

    if (!daysEl || !hoursEl || !minutesEl || !secondsEl) {
      return;
    }

    const targetAttr = container.dataset.target || "2026-04-15";
    const [year, month, day] = targetAttr.split("-").map(Number);
    const targetDate = new Date(year, month - 1, day, 0, 0, 0);

    function update() {
      const now = new Date();
      const diff = targetDate.getTime() - now.getTime();

      if (diff <= 0) {
        daysEl.textContent = "00";
        hoursEl.textContent = "00";
        minutesEl.textContent = "00";
        secondsEl.textContent = "00";
        if (noteEl) {
          noteEl.textContent =
            translations[currentLang]?.["proto.countdown.note"] || "Prototype milestone reached.";
        }
        return true;
      }

      const totalSeconds = Math.floor(diff / 1000);
      const days = Math.floor(totalSeconds / 86400);
      const hours = Math.floor((totalSeconds % 86400) / 3600);
      const minutes = Math.floor((totalSeconds % 3600) / 60);
      const seconds = totalSeconds % 60;

      daysEl.textContent = formatTime(days);
      hoursEl.textContent = formatTime(hours);
      minutesEl.textContent = formatTime(minutes);
      secondsEl.textContent = formatTime(seconds);

      return false;
    }

    update();
    const interval = setInterval(() => {
      if (update()) {
        clearInterval(interval);
      }
    }, 1000);
  }

  countdownTargets.forEach(setupCountdown);

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("in-view");
          observer.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.18 }
  );

  document.querySelectorAll(".reveal").forEach((section) => observer.observe(section));
});
